//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMedicalSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiseasesProcedureMpiapng
    {
        public int ID { get; set; }
        public int ProcedureID { get; set; }
        public int DiseaseID { get; set; }
    
        public virtual Disease Disease { get; set; }
        public virtual ProcedureType ProcedureType { get; set; }
    }
}
