//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMedicalSolution.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PatientMgmtEntities : DbContext
    {
        public PatientMgmtEntities()
            : base("name=PatientMgmtEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public DbSet<Disease> Diseases { get; set; }
        public DbSet<DiseaseType> DiseaseTypes { get; set; }
        public DbSet<InsuranceCardPicture> InsuranceCardPictures { get; set; }
        public DbSet<InsuranceType> InsuranceTypes { get; set; }
        public DbSet<IntakeFormHead> IntakeFormHeads { get; set; }
        public DbSet<InterferingCondition> InterferingConditions { get; set; }
        public DbSet<MedicalNecessity> MedicalNecessities { get; set; }
        public DbSet<Office> Offices { get; set; }
        public DbSet<PatientDiseas> PatientDiseases { get; set; }
        public DbSet<PatientHistory> PatientHistories { get; set; }
        public DbSet<PatientInterferingCondition> PatientInterferingConditions { get; set; }
        public DbSet<PatientProcedure> PatientProcedures { get; set; }
        public DbSet<Patient> Patients { get; set; }
        public DbSet<PatientSymtom> PatientSymtoms { get; set; }
        public DbSet<ProcedureType> ProcedureTypes { get; set; }
        public DbSet<Staff> Staffs { get; set; }
        public DbSet<Status> Statuses { get; set; }
        public DbSet<Symptom> Symptoms { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<UserRole> UserRoles { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
