//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMedicalSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntakeFormHead
    {
        public IntakeFormHead()
        {
            this.PatientDiseases = new HashSet<PatientDiseas>();
            this.PatientInterferingConditions = new HashSet<PatientInterferingCondition>();
            this.PatientSymtoms = new HashSet<PatientSymtom>();
        }
    
        public int ID { get; set; }
        public int HistoryID { get; set; }
        public string HaveSupportDevice { get; set; }
        public bool isPregnant { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ICollection<PatientDiseas> PatientDiseases { get; set; }
        public virtual ICollection<PatientInterferingCondition> PatientInterferingConditions { get; set; }
        public virtual ICollection<PatientSymtom> PatientSymtoms { get; set; }
    }
}
