//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMedicalSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.InsuranceCardPictures = new HashSet<InsuranceCardPicture>();
            this.PatientHistories = new HashSet<PatientHistory>();
            this.PatientReports = new HashSet<PatientReport>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime DOB { get; set; }
        public string Gender { get; set; }
        public string IDNumber { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ICollection<InsuranceCardPicture> InsuranceCardPictures { get; set; }
        public virtual ICollection<PatientHistory> PatientHistories { get; set; }
        public virtual ICollection<PatientReport> PatientReports { get; set; }
    }
}
