//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMedicalSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientProcedure
    {
        public int ID { get; set; }
        public int HistoryID { get; set; }
        public int ProcedureTypeID { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
        public string PhysicianRemarks { get; set; }
        public Nullable<bool> isApprovedByPhysician { get; set; }
        public Nullable<int> PhysicianID { get; set; }
        public Nullable<System.DateTime> PhysicianApprovedDate { get; set; }
        public string SpecialistRemarks { get; set; }
        public Nullable<bool> isApprovedBySpecialist { get; set; }
        public Nullable<int> SpecialistID { get; set; }
        public Nullable<System.DateTime> SpecialistApprovedDate { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual PatientHistory PatientHistory { get; set; }
        public virtual ProcedureType ProcedureType { get; set; }
    }
}
