//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMedicalSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcedureType
    {
        public ProcedureType()
        {
            this.PatientProcedures = new HashSet<PatientProcedure>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public bool isSelected { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual ICollection<PatientProcedure> PatientProcedures { get; set; }
    }
}
